### ISSUE TITLE
AccessViolation on some virtual methods

### ISSUE THREAD

**Issue by dr4cul4** [Virtuoze/NConcern#2]
In loop:

```
                                var _address = (long*)(type.TypeHandle.Value.ToInt64() + 0x40);
                                _address = (long*)(*_address);
                                foreach (var _method in type.Methods())
                                {
                                    _method.Prepare();
                                    if (_method.IsVirtual)
                                    {
                                        var _pointer = _method.Pointer().ToInt64();
                                        var _index = 0;
                                        while (true)
                                        {
                                            if (*(_address + _index) == _pointer)
                                            {
                                                _dictionary.Add(_method, new Entry(type, _method, new IntPtr(_address + _index), new Aspect.Activity(type, _method)));
                                                break;
                                            }
                                            _index++;
                                        }
                                    }
                                    else { _dictionary.Add(_method, new Entry(type, _method, new IntPtr((long*)_method.Handle().Value.ToPointer() + 1), new Aspect.Activity(type, _method))); }
                                }
```
Part `if (*(_address + _index) == _pointer)` throws an `AccessViolationException`

I've check memory view and there is actually 512 bytes at this point that program can't access:

Here is output from Immediate Window:
```
*(_address + _index)
Cannot dereference '_address + _index'. The pointer is not valid.
*(_address + (_index - 1))
0
*(_address + (_index + 511))
Cannot dereference '_address + (_index + 511)'. The pointer is not valid.
*(_address + (_index + 512))
140714883809280
_address
0x00007ffabc955970
    *_address: 140715314912248
_index
144082
```

Some methods before this are pinpointed corrrectly dough. Class has 151 methods and this one in particular is number 39. Unfortunately AccessViolationException can't be catched so this is a dead end to me now.
---- EDIT ----
Tried to replicate the problem on example code, but i came across more problems than I would like.

Try those:

```
    [ServiceContract]
    public class Calc
    {
        [OperationContract]
        public virtual int Divide(int a, int b)
        {
            return 0;
        }
    }

    [ServiceContract]
    public class Calculator : Calc
    {
        [OperationContract]
        public int Add(int a, int b)
        {
            return a + b;
        }

        [OperationContract]
        public override int Divide(int a, int b)
        {
            return a / b;
        }
    }
```
or
```
    [ServiceContract]
    public abstract class Calc
    {
        [OperationContract]
        public abstract int Add(int a, int b)

        [OperationContract]
        public virtual int Divide(int a, int b)
        {
            return 0;
        }
    }

    [ServiceContract]
    public class Calculator : Calc
    {
        [OperationContract]
        public override int Add(int a, int b)
        {
            return a + b;
        }

        [OperationContract]
        public override int Divide(int a, int b)
        {
            return a / b;
        }
    }
```

**Comment by Virtuoze** [comment]
Hi, thank you to share you issue, I will analyze it to find a fix. Parallel to this, I am working on a postbuild process to allow an alternative to inteception mechanism compatible with current NConcern API.

**Comment by dr4cul4** [comment]
I noticed that on that class in particular none of virtual methods can't be found. I've inspected Harmony which does similar thing in Mono, but they use native calls to mono libs instead of lookup.

**Comment by dr4cul4** [comment]
Later at home I will check if this would do (since virtual method is declared in class)

if (_method.IsVirtual && _method.DeclaringType != type)

**Comment by dr4cul4** [comment]
Didn't help, but I stumbled upon some thing. mscoreei.dll has two interesting functions exposed: `GetTargetForVTableEntry `and `SetTargetForVTableEntry` but I was unable to find any useful information about those functions usage.

**Comment by Virtuoze** [comment]
Thank you for trying... Another project I prepared may help you to get your code work asap. Indeed, I already tell you that I work on a postbuild process based on mono.cecil to inject some kind of "transparents handles" to help differents frameworks to build patterns & features. I planned to publish it this week as a nuget package. NConcern will be able to detect theses "handles" and choose more reliable interception mechanism to inject Aspects. In practice, it is not a direct dependency but an optional dependency to support non debuggable code, generics and more while keeping performance & the capability to inject/rollback at runtime. This project should become a foundation for multiple projects I planned (legacy mock framework for example). I will not miss to keep you updated on this topic.
