### ISSUE TITLE
FatalExecutionEngineError on Basic Example

### ISSUE THREAD

**Issue by MarcoGuzzetti** [Virtuoze/NConcern#3]
Hi,
I've an issue with the basic example, when I try to weave methods decorated with an attribute. In detail at line 44 of Program.cs (NConcern.Example.Basic) I have an FatalExecutionEngineError. 
Can you verify this? I've missed some settings?

Thank you!

**Comment by Virtuoze** [comment]
It seems issue is related to issue #2. A major fix is under testing as transparent additional build action to guarantee interception and will release in few (2 or 3) days.

**Comment by dr4cul4** [comment]
I think this is a god place to update on this problem. It is still occurring at the moment with CNeptune and NConcern.

Difference is that first Weave and Release are fine, after second Weave something get's messed in memory, cause executing Weaved method will result in AccessViolationException (or FatalExecutionEngineError under debbugger) just after return call is made from Weaved method.

Basic example: Calculator.cs line 19 / Program.cs line 59.

**Comment by Virtuoze** [comment]
Hi,

**Comment by Virtuoze** [comment]
Hi, 

After investigations, I found what was wrong. Indeed, NConcern use some kind of unsafe instructions like **OpCodes.Calli** to call method through pointer. It seems that **DynamicMethod was collected by garbage collector** that produce FatalErrorException or AccessViolationException.

I just add an additional information that is the "current sequence method" representing by a list of effective methods for an aspect in a specific entry. Its role is to allow runtime code analysis for "future" and keep reference to theses methods to prevent garbage collection.

[Current Sequence Method](https://github.com/Virtuoze/NConcern/commit/9f08b6e12f405273490a1327ec34cb029ed9e850#diff-e5a3cc15050d65c6061dfb40f949e517)
