### ISSUE TITLE
Support for interception of types in 3rd-party assemblies

### ISSUE THREAD

**Issue by ismaelhamed** [Virtuoze/NConcern#9]
When I try to add some aspects to a type in a 3rd-party assembly, I get: 
`'type 'TYPE_NAME' is not managed by CNeptune and cannot be supervised.'`

**Comment by Virtuoze** [comment]
Hi,
3rd-party assembly is supported,  you just have to call manually CNeptune to inject stub to 3rd party.
Indeed CNeptune can be executed using csproj as target or directly dll/exe. 
When you install CNeptune nuget package a post build process is created to do it natively with build action provided by msbuild. 
As a conclusion, use CNeptune executable to prepare an altered 3rd party assembly.
